# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LiveRoomPlayground-iOS' do

  pod 'ZegoLiveRoom/AudioPlayer'
#  pod 'Nama', '~> 7.2.0'
  pod 'SVProgressHUD'

end
