# Uncomment the next line to define a global platform for your project

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'LiveRoomPlayground-iOS' do

  pod 'ZegoLiveRoom'
  pod 'FURenderKit', '~> 8.3.0'
  pod 'SVProgressHUD'

end
